CRITICAL - 2023-12-23 11:22:31 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 246.
 1 SYSTEMPATH\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-12-23 11:22:33 --> Uncaught Error: Class "Locale" not found in D:\xampp\htdocs\b2b\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\xampp\htdocs\b2b\system\Helpers\number_helper.php(55): format_number(4.0, 2, NULL, Array)
#1 D:\xampp\htdocs\b2b\system\Debug\BaseExceptionHandler.php(145): number_to_size(4.0, 2)
#2 D:\xampp\htdocs\b2b\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(4194304)
#3 D:\xampp\htdocs\b2b\system\Debug\BaseExceptionHandler.php(241): include('D:\\xampp\\htdocs...')
#4 D:\xampp\htdocs\b2b\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\xampp\htdocs\b2b\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\xampp\\htdocs...')
#6 D:\xampp\htdocs\b2b\system\Debug\Exceptions.php(146): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\xampp\htdocs\b2b\system\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\xampp\htdocs\b2b\system\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\xampp\htdocs\b2b\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-12-23 10:28:06 --> Undefined property: App\Controllers\Admin::$usersRow
in APPPATH\Controllers\Admin.php on line 51.
 1 APPPATH\Controllers\Admin.php(51): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Admin::$usersRow', 'D:\\xampp\\htdocs\\b2b\\app\\Controllers\\Admin.php', 51)
 2 APPPATH\Controllers\Admin.php(86): App\Controllers\Admin->header('Add addvehicle')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Admin->addvehicle()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-23 11:53:53 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\xampp\htdocs\b2b\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\xampp\htdocs\b2b\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'b2b', 3307, '', 0)
#1 D:\xampp\htdocs\b2b\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\b2b\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\b2b\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\b2b\app\Models\usersModel.php(20): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\b2b\app\Controllers\Home.php(26): App\Models\usersModel->isvalidate('1', '1')
#6 D:\xampp\htdocs\b2b\system\CodeIgniter.php(919): App\Controllers\Home->login()
#7 D:\xampp\htdocs\b2b\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xampp\htdocs\b2b\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\b2b\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\xampp\htdocs\b2b\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\xampp\htdocs\b2b\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\b2b\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\b2b\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\b2b\app\Models\usersModel.php(20): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\b2b\app\Controllers\Home.php(26): App\Models\usersModel->isvalidate('1', '1')
#5 D:\xampp\htdocs\b2b\system\CodeIgniter.php(919): App\Controllers\Home->login()
#6 D:\xampp\htdocs\b2b\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\xampp\htdocs\b2b\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\b2b\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-12-23 11:53:53 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `userName` = :userName:
AND `password` = :password:', [...], false)
 3 APPPATH\Models\usersModel.php(20): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(26): App\Models\usersModel->isvalidate('1', '1')
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Home->login()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-23 11:54:12 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\xampp\htdocs\b2b\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\xampp\htdocs\b2b\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'b2b', 3307, '', 0)
#1 D:\xampp\htdocs\b2b\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\b2b\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\b2b\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\b2b\app\Models\usersModel.php(20): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\b2b\app\Controllers\Home.php(26): App\Models\usersModel->isvalidate('1', '1')
#6 D:\xampp\htdocs\b2b\system\CodeIgniter.php(919): App\Controllers\Home->login()
#7 D:\xampp\htdocs\b2b\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xampp\htdocs\b2b\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\b2b\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\xampp\htdocs\b2b\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\xampp\htdocs\b2b\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\b2b\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\b2b\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\b2b\app\Models\usersModel.php(20): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\b2b\app\Controllers\Home.php(26): App\Models\usersModel->isvalidate('1', '1')
#5 D:\xampp\htdocs\b2b\system\CodeIgniter.php(919): App\Controllers\Home->login()
#6 D:\xampp\htdocs\b2b\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\xampp\htdocs\b2b\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\b2b\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-12-23 11:54:12 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `userName` = :userName:
AND `password` = :password:', [...], false)
 3 APPPATH\Models\usersModel.php(20): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(26): App\Models\usersModel->isvalidate('1', '1')
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Home->login()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-23 16:50:43 --> syntax error, unexpected token ";", expecting variable or "{" or "$"
in APPPATH\Views\home.php on line 14.
 1 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1188): CodeIgniter\View\View->render('home', [], true)
 3 APPPATH\Controllers\Admin.php(56): view('home', [...])
 4 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Admin->index()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-23 17:30:47 --> ini_set(): Session ini settings cannot be changed after headers have already been sent
in SYSTEMPATH\Session\Handlers\FileHandler.php on line 72.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'ini_set(): Session ini settings cannot be changed after headers have already been sent', 'D:\\xampp\\htdocs\\b2b\\system\\Session\\Handlers\\FileHandler.php', 72)
 2 SYSTEMPATH\Session\Handlers\FileHandler.php(72): ini_set('session.save_path', 'D:\\xampp\\htdocs\\b2b\\writable\\session')
 3 SYSTEMPATH\Config\Services.php(685): CodeIgniter\Session\Handlers\FileHandler->__construct(Object(Config\Session), '::1')
 4 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 5 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 6 SYSTEMPATH\Config\Services.php(663): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 7 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
 8 SYSTEMPATH\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', [])
 9 APPPATH\Controllers\Admin.php(39): session()
10 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\Admin->__construct()
11 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
12 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-23 17:33:38 --> ini_set(): Session ini settings cannot be changed after headers have already been sent
in SYSTEMPATH\Session\Handlers\FileHandler.php on line 72.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'ini_set(): Session ini settings cannot be changed after headers have already been sent', 'D:\\xampp\\htdocs\\b2b\\system\\Session\\Handlers\\FileHandler.php', 72)
 2 SYSTEMPATH\Session\Handlers\FileHandler.php(72): ini_set('session.save_path', 'D:\\xampp\\htdocs\\b2b\\writable\\session')
 3 SYSTEMPATH\Config\Services.php(685): CodeIgniter\Session\Handlers\FileHandler->__construct(Object(Config\Session), '::1')
 4 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 5 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 6 SYSTEMPATH\Config\Services.php(663): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 7 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
 8 SYSTEMPATH\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', [])
 9 APPPATH\Controllers\Admin.php(39): session()
10 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\Admin->__construct()
11 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
12 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-23 17:33:59 --> ini_set(): Session ini settings cannot be changed after headers have already been sent
in SYSTEMPATH\Session\Handlers\FileHandler.php on line 72.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'ini_set(): Session ini settings cannot be changed after headers have already been sent', 'D:\\xampp\\htdocs\\b2b\\system\\Session\\Handlers\\FileHandler.php', 72)
 2 SYSTEMPATH\Session\Handlers\FileHandler.php(72): ini_set('session.save_path', 'D:\\xampp\\htdocs\\b2b\\writable\\session')
 3 SYSTEMPATH\Config\Services.php(685): CodeIgniter\Session\Handlers\FileHandler->__construct(Object(Config\Session), '::1')
 4 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 5 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 6 SYSTEMPATH\Config\Services.php(663): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 7 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
 8 SYSTEMPATH\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', [])
 9 APPPATH\Controllers\Admin.php(39): session()
10 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\Admin->__construct()
11 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
12 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-23 17:34:39 --> ini_set(): Session ini settings cannot be changed after headers have already been sent
in SYSTEMPATH\Session\Handlers\FileHandler.php on line 72.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'ini_set(): Session ini settings cannot be changed after headers have already been sent', 'D:\\xampp\\htdocs\\b2b\\system\\Session\\Handlers\\FileHandler.php', 72)
 2 SYSTEMPATH\Session\Handlers\FileHandler.php(72): ini_set('session.save_path', 'D:\\xampp\\htdocs\\b2b\\writable\\session')
 3 SYSTEMPATH\Config\Services.php(685): CodeIgniter\Session\Handlers\FileHandler->__construct(Object(Config\Session), '::1')
 4 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 5 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 6 SYSTEMPATH\Config\Services.php(663): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 7 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
 8 SYSTEMPATH\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', [])
 9 APPPATH\Controllers\Admin.php(39): session()
10 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\Admin->__construct()
11 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
12 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-23 17:35:38 --> ini_set(): Session ini settings cannot be changed after headers have already been sent
in SYSTEMPATH\Session\Handlers\FileHandler.php on line 72.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'ini_set(): Session ini settings cannot be changed after headers have already been sent', 'D:\\xampp\\htdocs\\b2b\\system\\Session\\Handlers\\FileHandler.php', 72)
 2 SYSTEMPATH\Session\Handlers\FileHandler.php(72): ini_set('session.save_path', 'D:\\xampp\\htdocs\\b2b\\writable\\session')
 3 SYSTEMPATH\Config\Services.php(685): CodeIgniter\Session\Handlers\FileHandler->__construct(Object(Config\Session), '::1')
 4 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 5 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 6 SYSTEMPATH\Config\Services.php(663): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 7 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
 8 SYSTEMPATH\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', [])
 9 APPPATH\Controllers\Admin.php(39): session()
10 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\Admin->__construct()
11 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
12 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-23 17:51:40 --> ini_set(): Session ini settings cannot be changed after headers have already been sent
in SYSTEMPATH\Session\Handlers\FileHandler.php on line 72.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'ini_set(): Session ini settings cannot be changed after headers have already been sent', 'D:\\xampp\\htdocs\\b2b\\system\\Session\\Handlers\\FileHandler.php', 72)
 2 SYSTEMPATH\Session\Handlers\FileHandler.php(72): ini_set('session.save_path', 'D:\\xampp\\htdocs\\b2b\\writable\\session')
 3 SYSTEMPATH\Config\Services.php(685): CodeIgniter\Session\Handlers\FileHandler->__construct(Object(Config\Session), '::1')
 4 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 5 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 6 SYSTEMPATH\Config\Services.php(663): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 7 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
 8 SYSTEMPATH\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', [])
 9 APPPATH\Controllers\Admin.php(39): session()
10 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\Admin->__construct()
11 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
12 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-23 17:54:10 --> Maximum execution time of 120 seconds exceeded
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-12-23 18:01:32 --> Undefined array key "LOADING_POINT"
in APPPATH\Views\auto_fill_rate\auto_fill_rateList.php on line 28.
 1 APPPATH\Views\auto_fill_rate\auto_fill_rateList.php(28): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "LOADING_POINT"', 'D:\\xampp\\htdocs\\b2b\\app\\Views\\auto_fill_rate\\auto_fill_rateList.php', 28)
 2 SYSTEMPATH\View\View.php(226): include('D:\\xampp\\htdocs\\b2b\\app\\Views\\auto_fill_rate\\auto_fill_rateList.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1188): CodeIgniter\View\View->render('auto_fill_rate/auto_fill_rateList', [], true)
 5 APPPATH\Controllers\Admin.php(472): view('auto_fill_rate/auto_fill_rateList', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Admin->auto_fill_rateList()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-23 18:03:08 --> Array to string conversion
in APPPATH\Views\excel\uplode_form.php on line 17.
 1 APPPATH\Views\excel\uplode_form.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'D:\\xampp\\htdocs\\b2b\\app\\Views\\excel\\uplode_form.php', 17)
 2 SYSTEMPATH\View\View.php(226): include('D:\\xampp\\htdocs\\b2b\\app\\Views\\excel\\uplode_form.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1188): CodeIgniter\View\View->render('excel/uplode_form', [], true)
 5 APPPATH\Controllers\Admin.php(533): view('excel/uplode_form', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Admin->excel()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-23 18:04:45 --> Undefined property: stdClass::$Freight_PER_MT
in APPPATH\Models\auto_fill_rateMoled.php on line 98.
 1 APPPATH\Models\auto_fill_rateMoled.php(98): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$Freight_PER_MT', 'D:\\xampp\\htdocs\\b2b\\app\\Models\\auto_fill_rateMoled.php', 98)
 2 APPPATH\Controllers\Admin.php(741): App\Models\auto_fill_rateMoled->getRateFor('2309574', 'SILLOD')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Admin->frontupload()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-23 18:06:46 --> Undefined property: stdClass::$Freight_PER_MT
in APPPATH\Models\auto_fill_rateMoled.php on line 98.
 1 APPPATH\Models\auto_fill_rateMoled.php(98): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$Freight_PER_MT', 'D:\\xampp\\htdocs\\b2b\\app\\Models\\auto_fill_rateMoled.php', 98)
 2 APPPATH\Controllers\Admin.php(741): App\Models\auto_fill_rateMoled->getRateFor('2309574', 'SILLOD')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Admin->entry_import()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-23 18:24:48 --> Call to undefined method CodeIgniter\Session\Session::set_flashdata()
in APPPATH\Controllers\Admin.php on line 709.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Admin->entry_import()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-23 18:30:50 --> Illegal offset type
in APPPATH\Controllers\Admin.php on line 696.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Admin->entry_import()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-23 18:31:48 --> Illegal offset type
in APPPATH\Controllers\Admin.php on line 696.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Admin->entry_import()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-23 19:16:00 --> Attempt to read property "comission_f" on null
in APPPATH\Views\transport_entry\dino_details.php on line 18.
 1 APPPATH\Views\transport_entry\dino_details.php(18): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "comission_f" on null', 'D:\\xampp\\htdocs\\b2b\\app\\Views\\transport_entry\\dino_details.php', 18)
 2 SYSTEMPATH\View\View.php(226): include('D:\\xampp\\htdocs\\b2b\\app\\Views\\transport_entry\\dino_details.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1188): CodeIgniter\View\View->render('transport_entry/dino_details', [], true)
 5 APPPATH\Controllers\Admin.php(1175): view('transport_entry/dino_details', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Admin->dinoDetails('4152284271')
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-23 19:16:25 --> Undefined variable $pump
in APPPATH\Views\transport_entry\dino_details.php on line 40.
 1 APPPATH\Views\transport_entry\dino_details.php(40): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $pump', 'D:\\xampp\\htdocs\\b2b\\app\\Views\\transport_entry\\dino_details.php', 40)
 2 SYSTEMPATH\View\View.php(226): include('D:\\xampp\\htdocs\\b2b\\app\\Views\\transport_entry\\dino_details.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1188): CodeIgniter\View\View->render('transport_entry/dino_details', [], true)
 5 APPPATH\Controllers\Admin.php(1175): view('transport_entry/dino_details', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Admin->dinoDetails('4152284271')
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-23 19:16:36 --> Undefined array key "user"
in APPPATH\Views\transport_entry\dino_details.php on line 47.
 1 APPPATH\Views\transport_entry\dino_details.php(47): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "user"', 'D:\\xampp\\htdocs\\b2b\\app\\Views\\transport_entry\\dino_details.php', 47)
 2 SYSTEMPATH\View\View.php(226): include('D:\\xampp\\htdocs\\b2b\\app\\Views\\transport_entry\\dino_details.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1188): CodeIgniter\View\View->render('transport_entry/dino_details', [], true)
 5 APPPATH\Controllers\Admin.php(1175): view('transport_entry/dino_details', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Admin->dinoDetails('4152284271')
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
